In [24]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [25]:
df = pd.read_csv("../dataset/raw/UNSW_NB15_training-set.csv")

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (82332, 45)

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

In [27]:
selected_features = [
    "dur",
    "proto",
    "state",
    "spkts",
    "dpkts",
    "sbytes",
    "dbytes",
    "rate",
    "sttl",
    "dttl"
]

df = df[selected_features + ["attack_cat"]]

print("Selected Columns:")
print(df.columns.tolist())

df.head()

Selected Columns:
['dur', 'proto', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'attack_cat']

,dur,proto,state,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,attack_cat
0,0.000011,udp,INT,2,0,496,0,90909.0902,254,0,Normal
1,0.000008,udp,INT,2,0,1762,0,125000.0003,254,0,Normal
2,0.000005,udp,INT,2,0,1068,0,200000.0051,254,0,Normal
3,0.000006,udp,INT,2,0,900,0,166666.6608,254,0,Normal
4,0.000010,udp,INT,2,0,2126,0,100000.0025,254,0,Normal

In [28]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
dur           0
proto         0
state         0
spkts         0
dpkts         0
sbytes        0
dbytes        0
rate          0
sttl          0
dttl          0
attack_cat    0
dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder

categorical_columns = [
    "proto",
    "state"
]

encoders = {}

for column in categorical_columns:
    encoder = LabelEncoder()
    df[column] = encoder.fit_transform(df[column])
    encoders[column] = encoder

print(df.head())

        dur  proto  state  spkts  dpkts  sbytes  dbytes         rate  sttl  \
0  0.000011    117      4      2      0     496       0   90909.0902   254
1  0.000008    117      4      2      0    1762       0  125000.0003   254
2  0.000005    117      4      2      0    1068       0  200000.0051   254
3  0.000006    117      4      2      0     900       0  166666.6608   254
4  0.000010    117      4      2      0    2126       0  100000.0025   254

   dttl attack_cat
0     0     Normal
1     0     Normal
2     0     Normal
3     0     Normal
4     0     Normal

In [30]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(encoders["proto"], "../models/proto_encoder.pkl")
joblib.dump(encoders["state"], "../models/state_encoder.pkl")

print("✓ Encoders saved successfully!")

✓ Encoders saved successfully!

In [31]:
df["label"] = df["attack_cat"].apply(
    lambda x: 0 if x == "Normal" else 1
)

df.drop("attack_cat", axis=1, inplace=True)

print(df.head())

        dur  proto  state  spkts  dpkts  sbytes  dbytes         rate  sttl  \
0  0.000011    117      4      2      0     496       0   90909.0902   254
1  0.000008    117      4      2      0    1762       0  125000.0003   254
2  0.000005    117      4      2      0    1068       0  200000.0051   254
3  0.000006    117      4      2      0     900       0  166666.6608   254
4  0.000010    117      4      2      0    2126       0  100000.0025   254

   dttl  label
0     0      0
1     0      0
2     0      0
3     0      0
4     0      0

In [32]:
X = df.drop("label", axis=1)
y = df["label"]

print("Feature Shape:", X.shape)
print("Label Shape:", y.shape)

Feature Shape: (82332, 10)
Label Shape: (82332,)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Set:", X_train.shape)
print("Testing Set :", X_test.shape)

Training Set: (65865, 10)
Testing Set : (16467, 10)

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Scaling Complete")

Scaling Complete

In [35]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(scaler, "../models/scaler.pkl")

print("✓ New scaler saved.")

✓ New scaler saved.

In [36]:
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [20]:
scaler = joblib.load("../models/scaler.pkl")

print(scaler.n_features_in_)
print(scaler.feature_names_in_)

10
['dur' 'proto' 'state' 'spkts' 'dpkts' 'sbytes' 'dbytes' 'rate' 'sttl'
 'dttl']

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import joblib

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

pred = rf.predict(X_test)

print(classification_report(y_test, pred))
print("Accuracy:", accuracy_score(y_test, pred))

joblib.dump(rf, "../models/Random_Forest.pkl")

print("✓ Random Forest saved.")

              precision    recall  f1-score   support

           0       0.91      0.94      0.93      7400
           1       0.95      0.93      0.94      9067

    accuracy                           0.93     16467
   macro avg       0.93      0.93      0.93     16467
weighted avg       0.93      0.93      0.93     16467

Accuracy: 0.9322280925487338
✓ Random Forest saved.

In [22]:
import joblib

rf = joblib.load("../models/Random_Forest.pkl")

print("Number of features:", rf.n_features_in_)

Number of features: 10

In [11]:
import numpy as np

np.save("../dataset/processed/X_train.npy", X_train)
np.save("../dataset/processed/X_test.npy", X_test)

np.save("../dataset/processed/y_train.npy", y_train)
np.save("../dataset/processed/y_test.npy", y_test)

print("Training and Testing data saved.")

Training and Testing data saved.

In [12]:
import joblib

joblib.dump(
    scaler,
    "../models/scaler.pkl"
)

print("Scaler saved successfully.")

Scaler saved successfully.

In [13]:
feature_df = pd.DataFrame(
    {"Feature": selected_features}
)

feature_df.to_csv(
    "../dataset/processed/selected_features.csv",
    index=False
)

print("Selected features saved.")

Selected features saved.

In [14]:
joblib.dump(
    encoders,
    "../models/encoders.pkl"
)

print("Encoders saved.")

Encoders saved.

In [15]:
print("=" * 50)
print("PREPROCESSING COMPLETED")
print("=" * 50)

print("Training Samples :", X_train.shape)
print("Testing Samples  :", X_test.shape)

print("\nSelected Features:")
for feature in selected_features:
    print("-", feature)

print("\nFiles Saved:")
print("✔ X_train.npy")
print("✔ X_test.npy")
print("✔ y_train.npy")
print("✔ y_test.npy")
print("✔ scaler.pkl")
print("✔ encoders.pkl")
print("✔ selected_features.csv")

==================================================
PREPROCESSING COMPLETED
==================================================
Training Samples : (65865, 10)
Testing Samples  : (16467, 10)

Selected Features:
- dur
- proto
- state
- spkts
- dpkts
- sbytes
- dbytes
- rate
- sttl
- dttl

Files Saved:
✔ X_train.npy
✔ X_test.npy
✔ y_train.npy
✔ y_test.npy
✔ scaler.pkl
✔ encoders.pkl
✔ selected_features.csv

In [16]:
print(df.columns.tolist())

['dur', 'proto', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'label']

In [41]:
from scapy.all import rdpcap, IP, TCP, UDP, ICMP
from collections import defaultdict
import pandas as pd
import os

print("Reading pcap file...")
packets = rdpcap("../captures/small_local_traffic.pcapng")
print(f"Total packets read: {len(packets)}")

flows = defaultdict(lambda: {
    "start_time": None,
    "end_time": None,
    "spkts": 0,
    "dpkts": 0,
    "sbytes": 0,
    "dbytes": 0,
    "sttl": 0,
    "dttl": 0,
    "proto": ""
})

for pkt in packets:
    if not pkt.haslayer(IP):
        continue
    
    src_ip = pkt[IP].src
    dst_ip = pkt[IP].dst
    ttl = pkt[IP].ttl
    pkt_len = len(pkt)
    timestamp = float(pkt.time)
    
    if pkt.haslayer(TCP):
        sport = pkt[TCP].sport
        dport = pkt[TCP].dport
        proto = "tcp"
    elif pkt.haslayer(UDP):
        sport = pkt[UDP].sport
        dport = pkt[UDP].dport
        proto = "udp"
    elif pkt.haslayer(ICMP):
        sport = 0
        dport = 0
        proto = "icmp"
    else:
        sport = 0
        dport = 0
        proto = "other"
    
    # Group packets into flows
    flow_key = tuple(sorted([(src_ip, sport), (dst_ip, dport)])) + (proto,)
    flow = flows[flow_key]
    
    if flow["start_time"] is None or timestamp < flow["start_time"]:
        flow["start_time"] = timestamp
    if flow["end_time"] is None or timestamp > flow["end_time"]:
        flow["end_time"] = timestamp
    
    # Count packets and bytes
    if src_ip < dst_ip:
        flow["spkts"] += 1
        flow["sbytes"] += pkt_len
        flow["sttl"] = ttl
    else:
        flow["dpkts"] += 1
        flow["dbytes"] += pkt_len
        flow["dttl"] = ttl
    
    flow["proto"] = proto

print(f"Total flows extracted: {len(flows)}")

rows = []
for key, f in flows.items():
    dur = f["end_time"] - f["start_time"] if f["end_time"] and f["start_time"] else 0
    
    # Calculate 'rate' (Total packets per second)
    total_packets = f["spkts"] + f["dpkts"]
    rate = total_packets / dur if dur > 0 else 0
    
    # ONLY append the exact 11 features you need
    rows.append({
        "dur": round(dur, 6),
        "proto": f["proto"],
        "state": "CON",  # Default state for established flows
        "spkts": f["spkts"],
        "dpkts": f["dpkts"],
        "sbytes": f["sbytes"],
        "dbytes": f["dbytes"],
        "rate": round(rate, 4),
        "sttl": f["sttl"],
        "dttl": f["dttl"],
        "label": 0  # IMPORTANT: Change to 1 if this pcap contains attack traffic!
    })

local_df = pd.DataFrame(rows)

os.makedirs("../dataset/raw", exist_ok=True)
local_df.to_csv("../dataset/raw/local_traffic.csv", index=False)

print(f"Saved {len(local_df)} flows to ../dataset/raw/local_traffic.csv")
display(local_df.head())

Reading pcap file...
Total packets read: 1033
Total flows extracted: 61
Saved 61 flows to ../dataset/raw/local_traffic.csv

,dur,proto,state,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,label
0,0.475647,tcp,CON,4,6,1200,890,21.0240,64,42,0
1,1.237462,tcp,CON,10,12,2179,6380,17.7783,64,42,0
2,0.000000,other,CON,1,0,54,0,0.0000,1,0,0
3,0.025320,tcp,CON,1,1,55,70,78.9880,64,118,0
4,1.235583,tcp,CON,10,12,2179,6380,17.8054,64,42,0

In [42]:
import pandas as pd
import numpy as np

print("Loading datasets...")

unsw_df = pd.read_csv("../dataset/raw/UNSW_NB15_training-set.csv")

local_df = pd.read_csv("../dataset/raw/local_traffic.csv")

print(f"UNSW-NB15 shape: {unsw_df.shape}")
print(f"Local Traffic shape: {local_df.shape}")

Loading datasets...
UNSW-NB15 shape: (82332, 45)
Local Traffic shape: (61, 11)

In [43]:
# The exact 11 columns we have in our local traffic (10 features + 1 label)
common_columns = ['dur', 'proto', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'label']

# Subset UNSW-NB15 to ONLY keep these columns
unsw_subset = unsw_df[common_columns]
print(f"UNSW-NB15 subset shape: {unsw_subset.shape}")

# Merge them together
combined_df = pd.concat([unsw_subset, local_df], ignore_index=True)
print(f"Combined dataset shape: {combined_df.shape}")

# Separate Features (X) and Target (y)
X = combined_df.drop(columns=['label'])
y = combined_df['label']

print(f"\nFeatures (X) shape: {X.shape}")
print(f"Target (y) shape: {y.shape}")

UNSW-NB15 subset shape: (82332, 11)
Combined dataset shape: (82393, 11)

Features (X) shape: (82393, 10)
Target (y) shape: (82393,)

In [44]:
from sklearn.model_selection import train_test_split

print("Splitting data into Train (80%) and Test (20%)...")

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2, 
    random_state=42, 
    stratify=y # Keeps the Normal/Attack ratio identical in both sets
)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

Splitting data into Train (80%) and Test (20%)...
X_train shape: (65914, 10)
X_test shape: (16479, 10)
y_train shape: (65914,)
y_test shape: (16479,)

In [45]:
import pandas as pd

# The text columns in our 10 features
categorical_cols = ['proto', 'state']

print("Encoding categorical variables...")

# Convert text to numbers for the training data
X_train_encoded = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)

# Convert text to numbers for the test data
X_test_encoded = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# CRITICAL: Ensure the test set has the EXACT same columns as the train set
# If a category (like a rare protocol) only exists in the test set, this fills it with 0
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

print(f"Encoded X_train shape: {X_train_encoded.shape}")
print(f"Encoded X_test shape: {X_test_encoded.shape}")

Encoding categorical variables...
Encoded X_train shape: (65914, 145)
Encoded X_test shape: (16479, 145)

In [46]:
from sklearn.preprocessing import StandardScaler
import joblib
import os

print("Scaling numerical features...")

scaler = StandardScaler()

# CRITICAL: Fit ONLY on training data to prevent data leakage
X_train_scaled = scaler.fit_transform(X_train_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

# Save the scaler for your Flask app later
os.makedirs("../dataset/processed", exist_ok=True)
joblib.dump(scaler, "../dataset/processed/scaler.pkl")

print("✓ Scaler fitted and saved to ../dataset/processed/scaler.pkl!")

Scaling numerical features...
✓ Scaler fitted and saved to ../dataset/processed/scaler.pkl!

In [47]:
import numpy as np

print("Saving processed data to ../dataset/processed/...")

np.save("../dataset/processed/X_train.npy", X_train_scaled)
np.save("../dataset/processed/X_test.npy", X_test_scaled)
np.save("../dataset/processed/y_train.npy", y_train.values)
np.save("../dataset/processed/y_test.npy", y_test.values)

print("\n" + "="*60)
print("SUCCESS! All data saved.")
print("You can now close this notebook and run week1_models.ipynb")
print("="*60)

Saving processed data to ../dataset/processed/...

============================================================
SUCCESS! All data saved.
You can now close this notebook and run week1_models.ipynb
============================================================