In [9]:
import numpy as np
import os

# Define the path to your processed data
data_dir = "../dataset/processed"

# Load the train and test sets (These have 145 features!)
X_train = np.load(os.path.join(data_dir, "X_train.npy"))
y_train = np.load(os.path.join(data_dir, "y_train.npy"))
X_test = np.load(os.path.join(data_dir, "X_test.npy"))
y_test = np.load(os.path.join(data_dir, "y_test.npy"))

print("✓ Data loaded successfully!")
print(f"X_train shape: {X_train.shape}") # This should print (65914, 145)
print(f"y_train shape: {y_train.shape}")

✓ Data loaded successfully!
X_train shape: (65914, 145)
y_train shape: (65914,)

In [10]:
import os
import time
import joblib
import psutil
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score
)

os.makedirs("../models", exist_ok=True)
os.makedirs("../results", exist_ok=True)

models = {
    "Random_Forest": RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1),
    "AdaBoost": AdaBoostClassifier(n_estimators=100, random_state=42),
    "Gradient_Boosting": GradientBoostingClassifier(n_estimators=100, random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5, n_jobs=-1),
    "Naive_Bayes": GaussianNB()
}

results = []

for name, model in models.items():
    print("=" * 70)
    print(f"Training {name}")

    process = psutil.Process(os.getpid())
    cpu_before = psutil.cpu_percent(interval=None)
    ram_before = process.memory_info().rss

    # Train
    start_train = time.time()
    model.fit(X_train, y_train)
    end_train = time.time()

    cpu_after = psutil.cpu_percent(interval=None)
    ram_after = process.memory_info().rss

    # Predict
    start_predict = time.time()
    predictions = model.predict(X_test)
    end_predict = time.time()

    # Core Metrics
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    # Fixed Confusion Matrix
    tn, fp, fn, tp = confusion_matrix(y_test, predictions, labels=[0, 1]).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0

    # ROC-AUC
    if hasattr(model, "predict_proba"):
        try:
            probabilities = model.predict_proba(X_test)[:, 1]
            roc = roc_auc_score(y_test, probabilities)
        except Exception:
            roc = np.nan
    else:
        roc = np.nan

    # Save Model
    filename = f"../models/{name}.pkl"
    joblib.dump(model, filename)
    model_size = os.path.getsize(filename) / (1024 * 1024)

    cpu_usage = (cpu_before + cpu_after) / 2

    results.append({
        "Model": name,
        "Features": X_train.shape[1], 
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Specificity": specificity,
        "False Positive Rate": fpr,
        "ROC-AUC": roc,
        "CPU Usage (%)": cpu_usage,
        "RAM Usage (MB)": abs((ram_after - ram_before) / (1024 * 1024)),
        "Training Time (s)": end_train - start_train,
        "Prediction Time (s)": end_predict - start_predict,
        "Model Size (MB)": model_size
    })

    print(f"✓ {name} completed. | Specificity: {specificity:.4f} | FPR: {fpr:.4f} | Sum: {specificity + fpr:.4f}")

results_df = pd.DataFrame(results)
display(results_df)

results_df.to_csv("../results/base_models_results.csv", index=False)
print("\nAll base models trained successfully on 145 features!")

======================================================================
Training Random_Forest
✓ Random_Forest completed. | Specificity: 0.9397 | FPR: 0.0603 | Sum: 1.0000
======================================================================
Training AdaBoost
✓ AdaBoost completed. | Specificity: 0.9394 | FPR: 0.0606 | Sum: 1.0000
======================================================================
Training Gradient_Boosting
✓ Gradient_Boosting completed. | Specificity: 0.9541 | FPR: 0.0459 | Sum: 1.0000
======================================================================
Training KNN
✓ KNN completed. | Specificity: 0.7573 | FPR: 0.2427 | Sum: 1.0000
======================================================================
Training Naive_Bayes
✓ Naive_Bayes completed. | Specificity: 1.0000 | FPR: 0.0000 | Sum: 1.0000

,Model,Features,Accuracy,Precision,Recall,F1,Specificity,False Positive Rate,ROC-AUC,CPU Usage (%),RAM Usage (MB),Training Time (s),Prediction Time (s),Model Size (MB)
0,Random_Forest,145,0.931792,0.949417,0.925334,0.937221,0.939692,0.060308,0.979949,73.50,141.582031,4.338045,0.137492,55.924081
1,AdaBoost,145,0.849566,0.940021,0.776111,0.850239,0.939423,0.060577,0.939569,78.60,0.347656,25.532881,2.356770,0.062423
2,Gradient_Boosting,145,0.918138,0.959514,0.888717,0.922760,0.954128,0.045872,0.979421,67.75,28.156250,46.873317,0.213215,0.133583
3,KNN,145,0.832029,0.818228,0.893129,0.854039,0.757285,0.242715,0.945481,80.65,73.011719,0.181921,11.765013,73.421835
4,Naive_Bayes,145,0.546878,1.000000,0.176464,0.299991,1.000000,0.000000,0.589390,95.90,0.054688,0.367490,0.078769,0.005164

All base models trained successfully on 145 features!

In [11]:
import numpy as np
import os
import joblib

# 1. Load the new combined data
data_dir = "../dataset/processed"
X_train = np.load(os.path.join(data_dir, "X_train.npy"))
y_train = np.load(os.path.join(data_dir, "y_train.npy"))
X_test = np.load(os.path.join(data_dir, "X_test.npy"))
y_test = np.load(os.path.join(data_dir, "y_test.npy"))

print("✓ Data loaded!")

# 2. Load the 5 base models you just trained
models_dir = "../models"
rf = joblib.load(os.path.join(models_dir, "Random_Forest.pkl"))
ada = joblib.load(os.path.join(models_dir, "AdaBoost.pkl"))
gb = joblib.load(os.path.join(models_dir, "Gradient_Boosting.pkl"))
knn = joblib.load(os.path.join(models_dir, "KNN.pkl"))
nb = joblib.load(os.path.join(models_dir, "Naive_Bayes.pkl"))

print("✓ Base models loaded!")

✓ Data loaded!
✓ Base models loaded!

In [12]:
import time
import psutil
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.ensemble import VotingClassifier, StackingClassifier, RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

os.makedirs("../models", exist_ok=True)
os.makedirs("../results", exist_ok=True)

# 1. Load the NEWLY trained base models
models_dir = "../models"
rf = joblib.load(os.path.join(models_dir, "Random_Forest.pkl"))
ada = joblib.load(os.path.join(models_dir, "AdaBoost.pkl"))
gb = joblib.load(os.path.join(models_dir, "Gradient_Boosting.pkl"))
knn = joblib.load(os.path.join(models_dir, "KNN.pkl"))
nb = joblib.load(os.path.join(models_dir, "Naive_Bayes.pkl"))

# 2. Load the 145-feature data
data_dir = "../dataset/processed"
X_train = np.load(os.path.join(data_dir, "X_train.npy"))
y_train = np.load(os.path.join(data_dir, "y_train.npy"))
X_test = np.load(os.path.join(data_dir, "X_test.npy"))
y_test = np.load(os.path.join(data_dir, "y_test.npy"))

# 3. Define ALL 8 Ensemble Models
ensembles = {
    "Hard_Voting": VotingClassifier(estimators=[('rf', rf), ('gb', gb), ('knn', knn)], voting='hard'),
    "Soft_Voting": VotingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada)], voting='soft'),
    "Stacking_Top3_LR": StackingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada)], final_estimator=LogisticRegression(max_iter=1000)),
    "Stacking_Top3_GB": StackingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada)], final_estimator=GradientBoostingClassifier(random_state=42)),
    "Stacking_Top3_RF": StackingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada)], final_estimator=RandomForestClassifier(random_state=42, n_jobs=-1)),
    "Stacking_All_LR": StackingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada), ('knn', knn), ('nb', nb)], final_estimator=LogisticRegression(max_iter=1000)),
    "Stacking_All_GB": StackingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada), ('knn', knn), ('nb', nb)], final_estimator=GradientBoostingClassifier(random_state=42)),
    "Stacking_All_RF": StackingClassifier(estimators=[('rf', rf), ('gb', gb), ('ada', ada), ('knn', knn), ('nb', nb)], final_estimator=RandomForestClassifier(random_state=42, n_jobs=-1))
}

ensemble_results = []

for name, model in ensembles.items():
    print("=" * 70)
    print(f"Training {name}...")

    process = psutil.Process(os.getpid())
    cpu_before = psutil.cpu_percent(interval=None)
    ram_before = process.memory_info().rss

    start_train = time.time()
    model.fit(X_train, y_train)
    end_train = time.time()

    cpu_after = psutil.cpu_percent(interval=None)
    ram_after = process.memory_info().rss

    start_predict = time.time()
    predictions = model.predict(X_test)
    end_predict = time.time()

    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    tn, fp, fn, tp = confusion_matrix(y_test, predictions, labels=[0, 1]).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0

    roc = np.nan
    if hasattr(model, "predict_proba"):
        try:
            probabilities = model.predict_proba(X_test)[:, 1]
            roc = roc_auc_score(y_test, probabilities)
        except Exception:
            pass

    filename = f"../models/{name}.pkl"
    joblib.dump(model, filename)
    model_size = os.path.getsize(filename) / (1024 * 1024)

    ensemble_results.append({
        "Model": name,
        "Features": X_train.shape[1], # This will now correctly be 145
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Specificity": specificity,
        "False Positive Rate": fpr,
        "ROC-AUC": roc,
        "CPU Usage (%)": (cpu_before + cpu_after) / 2,
        "RAM Usage (MB)": abs((ram_after - ram_before) / (1024 * 1024)), 
        "Training Time (s)": end_train - start_train,
        "Prediction Time (s)": end_predict - start_predict,
        "Model Size (MB)": model_size
    })

    print(f"✓ {name} completed. | Specificity: {specificity:.4f} | FPR: {fpr:.4f} | Sum: {specificity + fpr:.4f}")

ensemble_df = pd.DataFrame(ensemble_results)
ensemble_df.to_csv("../results/ensemble_models_results.csv", index=False)
print("\n✓ All 8 ensemble models trained and saved!")

======================================================================
Training Hard_Voting...
✓ Hard_Voting completed. | Specificity: 0.9563 | FPR: 0.0437 | Sum: 1.0000
======================================================================
Training Soft_Voting...
✓ Soft_Voting completed. | Specificity: 0.9498 | FPR: 0.0502 | Sum: 1.0000
======================================================================
Training Stacking_Top3_LR...
✓ Stacking_Top3_LR completed. | Specificity: 0.9413 | FPR: 0.0587 | Sum: 1.0000
======================================================================
Training Stacking_Top3_GB...
✓ Stacking_Top3_GB completed. | Specificity: 0.9602 | FPR: 0.0398 | Sum: 1.0000
======================================================================
Training Stacking_Top3_RF...
✓ Stacking_Top3_RF completed. | Specificity: 0.9509 | FPR: 0.0491 | Sum: 1.0000
======================================================================
Training Stacking_All_LR...
✓ Stacking_All_LR completed. | Specificity: 0.9427 | FPR: 0.0573 | Sum: 1.0000
======================================================================
Training Stacking_All_GB...
✓ Stacking_All_GB completed. | Specificity: 0.9599 | FPR: 0.0401 | Sum: 1.0000
======================================================================
Training Stacking_All_RF...
✓ Stacking_All_RF completed. | Specificity: 0.9464 | FPR: 0.0536 | Sum: 1.0000

✓ All 8 ensemble models trained and saved!

In [13]:
base_df = pd.read_csv("../results/base_models_results.csv")
ensemble_df = pd.read_csv("../results/ensemble_models_results.csv")

final_df = pd.concat([base_df, ensemble_df], ignore_index=True)

# TABLE 1: PERFORMANCE
perf_metrics = ["Accuracy", "Precision", "Recall", "F1", "Specificity", "ROC-AUC"]
perf_df = final_df[["Model"] + perf_metrics].copy()
perf_df["False Positive Rate"] = final_df["False Positive Rate"]

ranked_perf = perf_df[perf_metrics].rank(ascending=False, method='average')
ranked_perf["False Positive Rate"] = perf_df["False Positive Rate"].rank(ascending=True, method='average')

perf_df["Average Performance Rank"] = ranked_perf.mean(axis=1).round(2)
perf_df = perf_df.sort_values("Average Performance Rank").reset_index(drop=True)
perf_df.insert(0, "Overall Rank", range(1, len(perf_df) + 1))
perf_df[perf_metrics + ["False Positive Rate"]] = perf_df[perf_metrics + ["False Positive Rate"]].round(4)

print("\n" + "="*80)
print("TABLE 1: PERFORMANCE EVALUATION (All 13 Models)")
print("="*80)
display(perf_df)

# TABLE 2: EFFICIENCY 
eff_metrics = ["Prediction Time (s)", "Model Size (MB)"]

eff_df = final_df[["Model"] + eff_metrics].copy()
ranked_eff = eff_df[eff_metrics].rank(ascending=True, method='average')

eff_df["Average Efficiency Rank"] = ranked_eff.mean(axis=1).round(2)
eff_df = eff_df.sort_values("Average Efficiency Rank").reset_index(drop=True)
eff_df.insert(0, "Overall Rank", range(1, len(eff_df) + 1))
eff_df[eff_metrics] = eff_df[eff_metrics].round(4)

print("\n" + "="*80)
print("TABLE 2: EFFICIENCY EVALUATION (All 13 Models)")
print("="*80)
display(eff_df)


perf_df.to_csv("../results/final_table1_performance.csv", index=False)
eff_df.to_csv("../results/final_table2_efficiency.csv", index=False)
print("\n✓ Final unified tables saved to ../results/!")

================================================================================
TABLE 1: PERFORMANCE EVALUATION (All 13 Models)
================================================================================

,Overall Rank,Model,Accuracy,Precision,Recall,F1,Specificity,ROC-AUC,False Positive Rate,Average Performance Rank
0,1,Stacking_All_GB,0.9337,0.9653,0.9122,0.9380,0.9599,0.9855,0.0401,3.29
1,2,Stacking_Top3_GB,0.9331,0.9655,0.9110,0.9375,0.9602,0.9854,0.0398,3.57
2,3,Soft_Voting,0.9342,0.9574,0.9214,0.9390,0.9498,0.9844,0.0502,4.43
3,4,Stacking_All_LR,0.9339,0.9519,0.9268,0.9391,0.9427,0.9843,0.0573,5.29
4,5,Hard_Voting,0.9303,0.9622,0.9091,0.9349,0.9563,NaN,0.0437,5.67
5,6,Stacking_Top3_LR,0.9336,0.9508,0.9273,0.9389,0.9413,0.9843,0.0587,6.00
6,7,Stacking_All_RF,0.9296,0.9544,0.9158,0.9347,0.9464,0.9809,0.0536,7.29
7,8,Stacking_Top3_RF,0.9274,0.9577,0.9082,0.9323,0.9509,0.9800,0.0491,7.43
8,9,Naive_Bayes,0.5469,1.0000,0.1765,0.3000,1.0000,0.5894,0.0000,7.71
9,10,Gradient_Boosting,0.9181,0.9595,0.8887,0.9228,0.9541,0.9794,0.0459,7.86
10,11,Random_Forest,0.9318,0.9494,0.9253,0.9372,0.9397,0.9799,0.0603,8.00
11,12,KNN,0.8320,0.8182,0.8931,0.8540,0.7573,0.9455,0.2427,11.71
12,13,AdaBoost,0.8496,0.9400,0.7761,0.8502,0.9394,0.9396,0.0606,11.71

================================================================================
TABLE 2: EFFICIENCY EVALUATION (All 13 Models)
================================================================================

,Overall Rank,Model,Prediction Time (s),Model Size (MB),Average Efficiency Rank
0,1,Naive_Bayes,0.0788,0.0052,1.0
1,2,Random_Forest,0.1375,55.9241,3.0
2,3,Gradient_Boosting,0.2132,0.1336,3.0
3,4,AdaBoost,2.3568,0.0624,5.0
4,5,Soft_Voting,0.8573,112.2414,5.0
5,6,Stacking_Top3_LR,1.3906,112.2422,6.5
6,7,Stacking_Top3_GB,0.9578,112.3757,6.5
7,8,Stacking_Top3_RF,1.5422,175.0887,8.0
8,9,KNN,11.7650,73.4218,9.0
9,10,Hard_Voting,7.7410,258.9584,9.5
10,11,Stacking_All_GB,8.7564,259.2293,11.0
11,12,Stacking_All_LR,9.1714,259.0952,11.5
12,13,Stacking_All_RF,9.1572,320.5455,12.0

✓ Final unified tables saved to ../results/!

In [8]:
import pandas as pd
import numpy as np

base_df = pd.read_csv("../results/base_models_results.csv")
ensemble_df = pd.read_csv("../results/ensemble_models_results.csv")
final_df = pd.concat([base_df, ensemble_df], ignore_index=True)

perf_metrics = ["Accuracy", "Precision", "Recall", "F1", "Specificity", "ROC-AUC"]
ranked_perf = final_df[perf_metrics].rank(ascending=False, method='average')
ranked_perf["False Positive Rate"] = final_df["False Positive Rate"].rank(ascending=True, method='average')
final_df["Avg Performance Rank"] = ranked_perf.mean(axis=1).round(2)

eff_metrics = ["Prediction Time (s)", "Model Size (MB)"]
ranked_eff = final_df[eff_metrics].rank(ascending=True, method='average')
final_df["Avg Efficiency Rank"] = ranked_eff.mean(axis=1).round(2)

final_df = final_df.sort_values("Avg Performance Rank").reset_index(drop=True)
final_df.insert(0, "Overall Rank", range(1, len(final_df) + 1))

cols_to_round = perf_metrics + ["False Positive Rate", "Avg Performance Rank", "Avg Efficiency Rank", "Prediction Time (s)", "Model Size (MB)"]
final_df[cols_to_round] = final_df[cols_to_round].round(4)

print("="*80)
print("MASTER OVERALL WINNER TABLE (All 13 Models)")
print("="*80)
display(final_df)

final_df.to_csv("../results/overall_winner_table.csv", index=False)
print("\n Successfully saved to ../results/overall_winner_table.csv")

================================================================================
MASTER OVERALL WINNER TABLE (All 13 Models)
================================================================================

,Overall Rank,Model,Features,Accuracy,Precision,Recall,F1,Specificity,False Positive Rate,ROC-AUC,CPU Usage (%),RAM Usage (MB),Training Time (s),Prediction Time (s),Model Size (MB),Avg Performance Rank,Avg Efficiency Rank
0,1,Stacking_All_GB,145,0.9337,0.9653,0.9122,0.9380,0.9599,0.0401,0.9855,79.00,182.648438,414.509351,10.3354,194.2310,2.86,12.0
1,2,Stacking_Top3_GB,145,0.9331,0.9655,0.9110,0.9375,0.9602,0.0398,0.9854,65.25,125.496094,429.482735,1.5524,108.9969,3.29,8.0
2,3,Soft_Voting,145,0.9342,0.9574,0.9214,0.9390,0.9498,0.0502,0.9844,89.30,64.695312,57.115240,1.4508,108.8626,4.00,6.5
3,4,Stacking_All_LR,145,0.9339,0.9519,0.9268,0.9391,0.9427,0.0573,0.9843,71.50,179.652344,476.705196,9.5758,194.0969,4.86,10.5
4,5,Hard_Voting,145,0.9303,0.9622,0.9091,0.9349,0.9563,0.0437,NaN,64.85,236.792969,30.760778,16.6120,193.9642,5.17,11.5
5,6,Stacking_Top3_LR,145,0.9336,0.9508,0.9273,0.9389,0.9413,0.0587,0.9843,87.40,308.277344,440.076083,1.4235,108.8634,5.57,6.5
6,7,Stacking_All_RF,145,0.9296,0.9544,0.9158,0.9347,0.9464,0.0536,0.9809,79.65,130.453125,403.896673,9.8112,255.5472,7.00,12.0
7,8,Random_Forest,10,0.9322,0.9500,0.9257,0.9377,0.9403,0.0597,0.9836,68.55,96.878906,2.720591,0.1468,52.5447,7.14,4.0
8,9,Stacking_Top3_RF,145,0.9274,0.9577,0.9082,0.9323,0.9509,0.0491,0.9800,66.45,74.917969,406.196133,1.8677,171.7099,7.14,9.0
9,10,Gradient_Boosting,10,0.9204,0.9592,0.8936,0.9252,0.9534,0.0466,0.9796,72.20,44.328125,9.909377,0.0224,0.1341,7.43,2.5
10,11,KNN,10,0.9075,0.9348,0.8943,0.9141,0.9235,0.0765,0.9661,26.25,5.339844,0.157388,0.6724,11.8064,11.00,4.5
11,12,AdaBoost,10,0.8765,0.9134,0.8570,0.8843,0.9004,0.0996,0.9582,76.40,-2.253906,6.676834,0.4008,0.0624,12.14,3.0
12,13,Naive_Bayes,10,0.5118,0.7635,0.1641,0.2702,0.9377,0.0623,0.8046,97.50,0.160156,0.043418,0.0096,0.0010,12.29,1.0

 Successfully saved to ../results/overall_winner_table.csv

In [14]:
import pandas as pd
import numpy as np
import os

# 1. Create a dummy dataframe with the exact 10 raw column names
cols = ['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'proto', 'state']
dummy_df = pd.DataFrame([[0, 0, 0, 0, 0, 0, 0, 0, 'tcp', 'CON']], columns=cols)

# 2. Apply the exact same One-Hot Encoding we used in preprocessing
encoded_df = pd.get_dummies(dummy_df, columns=['proto', 'state'], drop_first=True)

# 3. Save the 145 column names to your processed folder
save_path = r"C:\Users\DELL\OneDrive\Desktop\AlgoGuard\dataset\processed\encoded_columns.npy"
np.save(save_path, encoded_df.columns.tolist())

print(f"✓ Successfully created encoded_columns.npy with {len(encoded_df.columns)} columns!")

✓ Successfully created encoded_columns.npy with 8 columns!

In [15]:
import numpy as np
import pandas as pd

# 1. Load your actual training data
X_train = np.load(r"C:\Users\DELL\OneDrive\Desktop\AlgoGuard\dataset\processed\X_train.npy")

# 2. Load the column names we need to reconstruct
# The first 8 columns are numerical: dur, spkts, dpkts, sbytes, dbytes, rate, sttl, dttl
# The remaining 137 columns are one-hot encoded proto_* and state_*

# 3. Create the correct column names
numerical_cols = ['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl']

# We need to figure out what the one-hot encoded columns are
# Based on UNSW-NB15, common protocols and states are:
protocols = ['tcp', 'udp', 'icmp', 'arp', 'rarp']  # Add more if needed
states = ['CON', 'FIN', 'INT', 'REQ', 'RST', 'PAR', 'ECR', 'ECO', 'URP', 'URH', 'TXD', 'TSH']  # Add more if needed

# Create one-hot column names (drop_first=True means we skip the first category alphabetically)
proto_cols = [f'proto_{p}' for p in sorted(protocols)[1:]]  # Skip first (alphabetically)
state_cols = [f'state_{s}' for s in sorted(states)[1:]]  # Skip first (alphabetically)

# Combine all columns
all_columns = numerical_cols + proto_cols + state_cols

# 4. Save to the app folder
np.save(r"C:\Users\DELL\OneDrive\Desktop\AlgoGuard\app\encoded_columns.npy", all_columns)

print(f"✅ Created encoded_columns.npy with {len(all_columns)} columns")
print(f"Numerical: {len(numerical_cols)}, Proto: {len(proto_cols)}, State: {len(state_cols)}")

✅ Created encoded_columns.npy with 23 columns
Numerical: 8, Proto: 4, State: 11

In [16]:
import numpy as np
import pandas as pd
import joblib

# 1. Load the raw training data (before encoding)
X_train = np.load(r"C:\Users\DELL\OneDrive\Desktop\AlgoGuard\dataset\processed\X_train.npy")

# 2. We need to reconstruct the column names
# The first 8 columns are numerical, the rest are one-hot encoded
numerical_cols = ['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl']

# Load the scaler to check how many features it expects
scaler = joblib.load(r"C:\Users\DELL\OneDrive\Desktop\AlgoGuard\dataset\processed\scaler.pkl")
total_features = scaler.n_features_in_

print(f"Scaler expects {total_features} features")
print(f"Numerical columns: {len(numerical_cols)}")
print(f"One-hot encoded columns needed: {total_features - len(numerical_cols)}")

# 3. Create a dummy dataframe with all possible protocol and state values
# Based on UNSW-NB15 dataset
all_protocols = ['arp', 'icmp', 'tcp', 'udp']  # Alphabetically sorted
all_states = ['ACC', 'CLO', 'CON', 'ECO', 'ECR', 'FIN', 'INT', 'MAS', 'PAR', 'REQ', 'RST', 'TSH', 'TXD', 'URH', 'URP']

# Create one-hot encoded column names (drop_first=True skips the first alphabetically)
proto_cols = [f'proto_{p}' for p in all_protocols[1:]]  # Skip 'arp'
state_cols = [f'state_{s}' for s in all_states[1:]]  # Skip 'ACC'

# Combine all columns
all_columns = numerical_cols + proto_cols + state_cols

print(f"\nTotal columns created: {len(all_columns)}")
print(f"Protocol columns: {proto_cols}")
print(f"State columns: {state_cols}")

# 4. Save to the app folder
np.save(r"C:\Users\DELL\OneDrive\Desktop\AlgoGuard\app\encoded_columns.npy", all_columns)

print(f"\n✅ Saved {len(all_columns)} column names to app/encoded_columns.npy")

Scaler expects 145 features
Numerical columns: 8
One-hot encoded columns needed: 137

Total columns created: 25
Protocol columns: ['proto_icmp', 'proto_tcp', 'proto_udp']
State columns: ['state_CLO', 'state_CON', 'state_ECO', 'state_ECR', 'state_FIN', 'state_INT', 'state_MAS', 'state_PAR', 'state_REQ', 'state_RST', 'state_TSH', 'state_TXD', 'state_URH', 'state_URP']

✅ Saved 25 column names to app/encoded_columns.npy